### ISSUE TITLE
signature-remove not working on windows, 2020

### ISSUE THREAD

**Issue by deepwithin** [Lifka/mailtrack-signature-remove#3]
The **signature is not getting removed on its own,** as it should be. I tried clicking on the extension too, when gmail compose is open, but nothing seems to be happening. **@Lifka** are you still using this extension you made? Is it working on your system?

_I am using chrome on windows 10._

**Comment by Lifka** [comment]
Hi,

I don't use the extension, it was just a script I made as a hobby a few years ago.
The issue is solved in this PR: https://github.com/Lifka/mailtrack-signature-remove/pull/5.
